# User config
author: "Jason Ganub"
tagline: "Home"
description: "Tibetan-American engineer at Gojek, Southeast Asia's largest ride-hailing unicorn. Previously hacking at Jago Coffee and Intel. Born in India, raised in Portland, and now working remotely in Indonesia. Passionate about travelling âœˆï¸, tennis ğŸ¾, space ğŸš€, surfing ğŸ„ğŸ»â€â™‚ï¸, and niche products ğŸ’¡"
keywords: "Jason Ganub, Jason, Loden, Ganub, Tibetan American, Tibetan-American"
email: "hi@jasonganub.com"
linkedin: "https://www.linkedin.com/in/jasonganub/"
twitter: "https://twitter.com/jasonganub"
github: "https://github.com/jasonganub"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Google services
google_analytics: G-KFVDP344PX